language: node_js

node_js:
- "6.10.3"

env:
  global:
    - CXX=g++-4.8

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

cache:
  yarn: true
  directories:
  - node_modules

before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi

script:
  - yarn run test
  - yarn run lint

after_script: "cat ./coverage/report-lcov/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
